apiVersion: v1
kind: Pod
metadata:
  name: cpu-demo
spec:
  containers:
  - name: cpu-demo-ctr
    image: vish/stress
    resources:
      requests:
        cpu: "200m"
      limits: 
        cpu: "1000m"
    args: ["--cpus", "0.2"]