apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-affinity-testing
  namespace: learning
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mrmotam
  template:
    metadata:
      labels:
        app: mrmotam
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values: ["mrmotam"]
              topologyKey: kubernetes.io/hostname
      containers:
      - name: nginxpod
        image: mrmotam/my-static-site:v1
        ports:
        - containerPort: 80 
